/*
 ============================================================================
   Web Solution Project, ID SW Development Department, LG ELECTRONICS INC., SEOUL, KOREA
   Copyright(c) 2021 by LG Electronics Inc.
   IDCAP extension version : 1.1.1
 ============================================================================
*/
var extIDCAPSecure,extRegisterIDCAPCloseHandler,extDisableIdcapConsoleLog,extWebWorker,isSubscribeParam,retry_count,idcap;
if(void 0===idcap)if("object"===typeof window)(function(){function b(a){1==idcap.isLogEnabled&&(a=1024<a.length?a.substring(0,1024):a,!0!==extWebWorker&&console.log(a))}function p(a,c){if(!0!==extWebWorker){var k="",l=document.createEvent("HTMLEvents");b(t("event received, ",c));l.initEvent(a,!0,!1);for(k in c)c.hasOwnProperty(k)&&(l[k]=c[k]);document.dispatchEvent(l)}}idcap={API_VERSION:"1.1.1",isRemoteInitialize:!1,isRemote:!1,remote_ip:"",isLogEnabled:!1,isMaxCount:4};var g=0,e=[{command_id:"0",
param_text:'{"command_id" : "0", "command" : "notify_sdk_version","parameters":{"idcap_js_extension_version" : "1.1.1"}}'}],h=[{command:"0",param_text:'{"command" : "0", "command" : "notify_sdk_version", "parameters":{"idcap_js_extension_version" : "1.1.1"}}'}],d=null,q=!1,v=!1,r=!1,A=null,w=null,F=null,B=!1,t=null,C=!1,z=!1,D=0,x="127.0.0.1";!0!==idcap.isLogEnabled?!0!==extWebWorker&&console.log("ID -  console log is disabled"):!0!==extWebWorker&&console.log("ID -  console log is enabled");b("check external value : extDisableIdcapConsoleLog = "+
extDisableIdcapConsoleLog+", extIDCAPSecure = "+extIDCAPSecure+", extRegisterIDCAPCloseHandler = "+extRegisterIDCAPCloseHandler);B=function(){var a=navigator.userAgent;a.match(/Windows/);a.match(/Macintosh/);a.match(/Mac OS X/);var c=a.match(/Web0S/),k=a.match(/SmartTV/),l=a.match(/WebAppManager/);b("UA = '"+a+"'");return c||k||l?(z=!1,idcap.isRemote=!1):z=idcap.isRemote=!0}();t=function(a,c){var k=[],l="",n;for(n in c)c.hasOwnProperty(n)&&k.push(n);k.sort();for(n=0;n<k.length;n+=1){var u=n,f=k,E=
c,m="",y="";var G=f[u];try{m=E[G],y=typeof m}catch(H){m="<unknown value>",y="unknown"}"function"===y?m="{/*function*/}":"object"===y?m=t("",m):"string"===y&&(m='"'+m+'"');l+='"'+G+'" : '+m;u<f.length-1&&(l+=", ")}return a+"{"+l+"}"};A=function(){b("initialize_idcap_websocket");v?b("websocket : connection is in progress"):(v=!0,0==z?!0!==extIDCAPSecure?(b("default idcap connection"),d=new WebSocket("ws://127.0.0.1:8153/hcap_command")):(b("secure idcap connection"),d=new WebSocket("wss://localhost:8154/idcap_command")):
(b("remote connection"),d="https:"===location.protocol?new WebSocket("wss://"+x+":8154/idcap_command"):new WebSocket("ws://"+x+":8153/idcap_command")),d.onopen=function(){b("websocket : onopen");v=!1;q=!0;setTimeout(w,5)},d.onmessage=function(a){a=JSON.parse(a.data);var c=a.command_id,k=a.command,l=a.result;b("ws.onmessage : "+JSON.stringify(a));if("event"===c)"debug_event_received"===k?(a.enable_log?!0!==extWebWorker&&console.log("idcap console log is enabled"):!0!==extWebWorker&&console.log("idcap console log is disabled"),
extDisableIdcapConsoleLog=!a.enable_log):p(k,a);else{if(0<e.length&&e[0].command_id===c){b(t("command_id = "+c+" received, ",a));try{l?e[0].successCB(a):e[0].failureCB(a)}catch(f){b(t("Error : ",f))}e.splice(0,1)}else{var n=0,u=!1;h.forEach(function(f){null!==f&&void 0!==f.command&&f.command===k&&(n=h.indexOf(f),u=!0)});if(u){if(h[n].onSuccess)try{h[n].onSuccess(a)}catch(f){b(t("exception : onSuccess : "+f))}}else b(t("invalid response from server ",a))}r=!1;w()}},d.onclose=function(){b("websocket : onclose");
r=q=v=!1;D+=1;b("retry-count",D);!z&&D<idcap.isMaxCount?setTimeout(w,50):b("Max retry - stop websocket connection try")},"onbeforeunload"===extRegisterIDCAPCloseHandler?window.onbeforeunload=function(){b("close idcap websocket in onbeforeunload handler");d.onclose=function(){};d.close()}:"onunload"===extRegisterIDCAPCloseHandler&&(window.onunload=function(){b("close idcap websocket in onunload handler");d.onclose=function(){};d.close()}))};w=function(){b("start_cmd_loop");if(!r){r=!0;if(q){if(0<e.length){b("webSocket sending");
b(t("command_id = "+e[0].command_id+" sent, ",JSON.parse(e[0].param_text)));d.send(e[0].param_text);return}}else A();r=!1}};F=function(a,c={}){if(null===a||""===a||void 0===a)b("[ERROR] Command should not be null.");else if(!1===a.toLowerCase().startsWith("idcap://"))b("[ERROR] wrong IDCAP command.");else if(Array.isArray(c))b("[ERROR] Command Parameter Error. param is Array type or not defined.");else{B&&b("[ERROR] IDCAP is unavailable on this browser.");g=1024<g?0:g+1;var k=g.toString(),l="";c.command_id=
k;c.command=a;l=JSON.stringify(c,null);b("param_text : "+l);for(name in c)"subscribe"===name&&c.hasOwnProperty("subscribe")&&!0===c.subscribe&&(C=!0);if(C)h.forEach(function(f){null!==f&&void 0!==f.command&&f.command===c.command?b("already registered. : "+a):h[h.length]={command:a,param_text:l,onSuccess:c.onSuccess,onFailure:c.onFailure}}),C=!1;else{var n=0,u=!1;h.forEach(function(f){null!==f&&void 0!==f.command&&f.command===c.command&&(n=h.indexOf(f),u=!0)});u=u?h.splice(n,1):!1}return new Promise((f,
E)=>{e.push({command_id:k,param_text:l,successCB:function(m){if(Object.prototype.hasOwnProperty.call(c,"onSuccess"))c.onSuccess(m);f(m)},failureCB:function(m){if(Object.prototype.hasOwnProperty.call(c,"onFailure"))c.onFailure(m);E(m)}});b(t("command_id = "+k+" added, ",e[e.length-1]));w()})}};B||setTimeout(w,200);idcap.remoteInitialize=function(a){b("remoteInitialize");x=a;b("remote = "+x);idcap.remote_ip=x;A();idcap.isRemoteInitialize=!0};idcap.remoteFinalize=function(){b("remoteFinalize");d.close();
d=null;idcap.remote_ip="";idcap.isRemoteInitialize=!1};idcap.request={};idcap.request=function(a,c){a=a.toLowerCase();return F(a,c)}})();else{var ev=require("events").EventEmitter;class b extends ev{constructor(p){super();let g=this;this.service=p;this.service.Request=function(e,h){"/"!=e.charAt(e.length-1)&&(e+="/");e+=h.method;var d={};Object.prototype.hasOwnProperty.call(h,"parameters")&&(d=h.parameters);var q={},v=function(r){!0===r.payload.returnValue?(q=r.payload,h.onSuccess(q)):(q.returnValue=
!1,q.errorCode=r.payload.errorCode,q.errorText=r.payload.errorText,h.onFailure(q))};g.service&&g.service.call(e,d,v)};this.subsForEvents=this.service.subscribe("luna://com.webos.service.idcapmw.mwcommand/getAllEvents",{subscribe:!0});this.subsForEvents.on("response",function(e){e=e.payload;if("event"===e.command_id)g.on_event_received(e.command,e)})}on_event_received(p,g){this.emit(p,g)}request(p,g){if(null!==p&&""!==p&&void 0!==p&&!Array.isArray(g)&&void 0!==g)return new Promise((e,h)=>{g.onSuccess&&
"function"===typeof g.onSuccess&&(e=g.onSuccess);g.onFailure&&"function"===typeof g.onFailure&&(h=g.onFailure);this.service.Request("luna://com.webos.service.idcapmw.mwcommand",{method:"/callidcap",parameters:{command:p,parameters:g.parameters},onSuccess:function(d){d.result?(delete d.returnValue,delete d.result,delete d.command_id,e(d)):(delete d.returnValue,delete d.result,delete d.command_id,h(d))},onFailure:function(d){delete d.returnValue;delete d.result;delete d.command_id;h(d)}})})}}module.exports=
b};
